services:
  web:
    build: .
    ports:
      - "8055:8055"
    volumes:
      - ./:/app
      - logs:/logs
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    command: gunicorn -c /app/gunicorn_config.py app:app

volumes:
  logs: